name: Deploy Site
on:
  push:
    branches:
      - master
jobs:
  deploy:
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          extended: true
          hugo-version: 0.98.0
      - name: Build
        run: hugo --minify
      - env:
          BRANCH: public
          FOLDER: public
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MESSAGE: 'Build: ({sha}) {msg}'
          REPO: self
          SQUASH_HISTORY: true
        name: Push
        uses: s0/git-publish-subdir-action@develop
